name: isbest
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- blast=2.6.0=boost1.60_0
- emboss=6.5.7=2
- pysftp=0.2.9=py36_0
- snakemake=4.0.0=py36_1
- aioeasywebdav=2.2.0=py36_0
- aiohttp=2.0.7=py36_0
- asn1crypto=0.22.0=py36_0
- async-timeout=1.2.1=py36_0
- biopython=1.70=np113py36_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.2=py36_1
- cryptography=1.9=py36_0
- docutils=0.13.1=py36_0
- dropbox=7.3.1=py36_0
- filechunkio=1.8=py36_1
- freetype=2.7=1
- ftputil=3.3.1=py36_0
- idna=2.5=py36_0
- jpeg=9b=0
- libffi=3.2.1=3
- libpng=1.6.28=0
- libtiff=4.0.6=7
- mmtf-python=1.0.7=py36_0
- msgpack-python=0.4.8=py36_0
- multidict=2.1.4=py36_0
- ncurses=5.9=10
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pandas=0.20.3=py36_1
- paramiko=2.2.1=py36_0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_0
- psutil=5.2.1=py36_0
- pyasn1=0.3.2=py36_0
- pycparser=2.18=py36_0
- pynacl=1.1.2=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_1
- readline=6.2=0
- reportlab=3.4.0=py36_0
- requests=2.18.3=py36_0
- setuptools=36.2.2=py36_0
- six=1.10.0=py36_1
- sqlite=3.13.0=1
- tk=8.5.19=2
- urllib3=1.21.1=py36_0
- wheel=0.29.0=py36_0
- wrapt=1.10.8=py36_0
- xz=5.2.2=0
- yaml=0.1.6=0
- yarl=0.10.0=py36_0
- zlib=1.2.11=0
- bcrypt=3.1.3=py36_0
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- pip:
  - awscli==1.11.108
  - botocore==1.5.71
  - colorama==0.3.7
  - jmespath==0.9.3
  - rsa==3.4.2
  - s3transfer==0.1.10
